# Generated by Django 6.0.6 on 2026-07-01 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('school_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام رسمی مدرسه')),
                ('short_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام کوتاه')),
                ('slogan', models.TextField(blank=True, null=True, verbose_name='شعار')),
                ('intro_text', models.TextField(blank=True, null=True, verbose_name='متن معرفی')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/settings/logo/', verbose_name='لوگو')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/settings/favicon/', verbose_name='فاوآیکون')),
                ('hero_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان hero')),
                ('hero_subtitle', models.TextField(blank=True, null=True, verbose_name='زیر عنوان hero')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='site/settings/heto/', verbose_name='تصویر hero')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('phone_primary', models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره تماس اصلی')),
                ('phone_secondary', models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره تماس دوم')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='ایمیل')),
                ('working_hours', models.CharField(blank=True, max_length=255, null=True, verbose_name='ساعت کاری')),
                ('instagram_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='لینک اینستاگرام')),
                ('telegram_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='لینک تلگرام')),
                ('eitaa_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='لینک ایتا')),
                ('founded_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='سال تأسیس')),
                ('students_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد دانش\u200cآموزان')),
                ('staff_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد کادر آموزشی')),
                ('achievements_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد افتخارات')),
                ('units_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد واحدها')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال است؟')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنظیمات سایت',
                'ordering': ['-is_active', '-updated_at', '-id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='unique_active_site_settings')],
            },
        ),
    ]
