export const apiEndpoints = {
  me: "me/",
  myPermissions: "me/permissions/",
  myUnits: "me/units/",
  siteSettings: "site-settings/",
  home: "home/",
  about: "about/",
  units: "units/",
  departments: "departments/",
  news: "news/",
  announcements: "announcements/",
  gallery: "gallery/",
  achievements: "achievements/",
  events: "events/",
  staff: "staff/",
  contact: "contact/",
  registration: "registration/",
  dashboard: {
    generalManager: "dashboard/general-manager/",
    unitManager: "dashboard/unit-manager/",
    media: "dashboard/media/",
    parents: "dashboard/parents/",
  },
  content: "content/",
  messages: "messages/",
  registrationRequests: "registration-requests/",
  auth: {
    login: "auth/login/",
    refresh: "auth/refresh/",
    logout: "auth/logout/",
    changePassword: "me/change-password/",
  },
  cms: {
    units: "cms/units/",
    news: "cms/news/",
    announcements: "cms/announcements/",
    gallery: "cms/gallery/",
    achievements: "cms/achievements/",
    events: "cms/events/",
    staff: "cms/staff/",
    messages: "cms/messages/",
    registrationRequests: "cms/registration-requests/",
    homeSlides: "cms/home-slides/",
  },
} as const;
