# Generated by Django 6.0.6 on 2026-07-01 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال است؟')),
                ('title', models.CharField(default='پیش\u200cثبت\u200cنام', max_length=255, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('is_open', models.BooleanField(db_index=True, default=True, verbose_name='ثبت\u200cنام باز است؟')),
                ('open_message', models.CharField(blank=True, max_length=500, null=True, verbose_name='پیام زمان باز بودن ثبت\u200cنام')),
                ('closed_message', models.CharField(blank=True, max_length=500, null=True, verbose_name='پیام زمان بسته بودن ثبت\u200cنام')),
                ('required_documents', models.JSONField(blank=True, default=list, verbose_name='مدارک مورد نیاز')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='توضیحات تکمیلی')),
            ],
            options={
                'verbose_name': 'اطلاعات ثبت\u200cنام',
                'verbose_name_plural': 'اطلاعات ثبت\u200cنام',
                'ordering': ('-is_active', '-updated_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='RegistrationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('student_full_name', models.CharField(max_length=255, verbose_name='نام و نام خانوادگی دانش\u200cآموز')),
                ('parent_full_name', models.CharField(max_length=255, verbose_name='نام و نام خانوادگی ولی')),
                ('parent_phone', models.CharField(max_length=50, verbose_name='شماره تماس ولی')),
                ('parent_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل ولی')),
                ('requested_grade', models.CharField(blank=True, max_length=100, null=True, verbose_name='پایه درخواستی')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('status', models.CharField(choices=[('new', 'جدید'), ('reviewing', 'در حال بررسی'), ('contacted', 'تماس گرفته\u200cشده'), ('accepted', 'پذیرفته\u200cشده'), ('rejected', 'ردشده'), ('archived', 'آرشیوشده')], db_index=True, default='new', max_length=20, verbose_name='وضعیت')),
                ('admin_note', models.TextField(blank=True, null=True, verbose_name='یادداشت مدیر')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='آدرس IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('requested_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registration_requests', to='units.schoolunit', verbose_name='واحد درخواستی')),
            ],
            options={
                'verbose_name': 'درخواست پیش\u200cثبت\u200cنام',
                'verbose_name_plural': 'درخواست\u200cهای پیش\u200cثبت\u200cنام',
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['status', 'created_at'], name='registratio_status_970ac1_idx'), models.Index(fields=['requested_unit', 'status'], name='registratio_request_edd36b_idx'), models.Index(fields=['created_at', 'id'], name='registratio_created_81afa9_idx')],
            },
        ),
    ]
