# Generated by Django 5.2.16 on 2026-08-09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0003_alter_registrationrequest_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="registrationrequest",
            name="submitted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.SET_NULL,
                related_name="submitted_registration_requests",
                to=settings.AUTH_USER_MODEL,
                verbose_name="ثبت‌شده توسط",
            ),
        ),
    ]
