# Generated by Django 6.0.6 on 2026-06-30 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال است؟')),
                ('title', models.CharField(default='تماس با ما', max_length=255, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره تماس اصلی')),
                ('phone_secondary', models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره تماس دوم')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('working_hours', models.CharField(blank=True, max_length=255, null=True, verbose_name='ساعات کاری')),
                ('map_url', models.URLField(blank=True, max_length=1000, null=True, verbose_name='لینک نقشه')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='عرض جغرافیایی')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='طول جغرافیایی')),
            ],
            options={
                'verbose_name': 'اطلاعات تماس',
                'verbose_name_plural': 'اطلاعات تماس',
                'ordering': ('-is_active', '-updated_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('full_name', models.CharField(max_length=255, verbose_name='نام و نام خانوادگی')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره تماس')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('subject', models.CharField(blank=True, max_length=255, null=True, verbose_name='موضوع')),
                ('message', models.TextField(verbose_name='متن پیام')),
                ('status', models.CharField(choices=[('new', 'جدید'), ('seen', 'دیده\u200cشده'), ('answered', 'پاسخ\u200cداده\u200cشده'), ('archived', 'آرشیوشده')], db_index=True, default='new', max_length=20, verbose_name='وضعیت')),
                ('admin_note', models.TextField(blank=True, null=True, verbose_name='یادداشت مدیر')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='آدرس IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
            ],
            options={
                'verbose_name': 'پیام تماس',
                'verbose_name_plural': 'پیام\u200cهای تماس',
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['status', 'created_at'], name='contact_con_status_402fcf_idx'), models.Index(fields=['created_at', 'id'], name='contact_con_created_a37007_idx')],
            },
        ),
    ]
