# Generated by Django 5.2.16 on 2026-07-30 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
        ('units', '0005_schoolunit_accepts_registration_schoolunit_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='message_type',
            field=models.CharField(choices=[('general', 'ارتباط عمومی'), ('criticism', 'انتقاد'), ('suggestion', 'پیشنهاد'), ('complaint', 'شکایت'), ('feedback', 'بازخورد')], db_index=True, default='general', max_length=20, verbose_name='نوع پیام'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='related_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_messages', to='units.schoolunit', verbose_name='واحد مرتبط'),
        ),
    ]
