export const apiEndpoints = {
  me: "me/",
  myPermissions: "me/permissions/",
  myUnits: "me/units/",
  siteSettings: "site-settings/",
  home: "home/",
  about: "about/",
  units: "units/",
  departments: "departments/",
  news: "news/",
  announcements: "announcements/",
  gallery: "gallery/",
  achievements: "achievements/",
  events: "events/",
  staff: "staff/",
  contact: "contact/",
  registration: "registration/",
  content: "content/",
  messages: "messages/",
  registrationRequests: "registration-requests/",
  dashboard: {
    context: "dashboard/context/",
    generalManager: "dashboard/general-manager/",
    unitManager: "dashboard/unit-manager/",
    media: "dashboard/media/",
    parents: "dashboard/parents/",
  },
  auth: {
    login: "auth/login/",
    refresh: "auth/refresh/",
    logout: "auth/logout/",
    changePassword: "me/change-password/",
  },
  cms: {
    units: "cms/units/",
    departments: "cms/departments/",
    news: "cms/news/",
    announcements: "cms/announcements/",
    gallery: "cms/gallery/",
    achievements: "cms/achievements/",
    events: "cms/events/",
    staff: "cms/staff/",
    messages: "cms/messages/",
    registrationRequests: "cms/registration-requests/",
    homeSlides: "cms/home-slides/",
    students: "cms/students/",
    content: "cms/content/",
    contentCategories: "cms/content/categories/",
    media: "cms/media/",
    internalMessages: "cms/internal-messages/",
    programs: "cms/programs/",
    services: "cms/services/",
    reports: "cms/reports/",
    settings: "cms/settings/",
    users: "cms/users/",
    staticPages: "cms/static-pages/",
  },
  parents: {
    children: "parents/children/",
    programs: "parents/programs/",
    registrations: "parents/registrations/",
  },
} as const;
