# Generated by Django 6.0.6 on 2026-07-01 07:45

import apps.staff.models
import apps.staff.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        ('units', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال است؟')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('scope', models.CharField(choices=[('school', 'کل مدرسه'), ('unit', 'واحد آموزشی')], db_index=True, default='school', max_length=20, verbose_name='محدوده انتشار')),
                ('full_name', models.CharField(max_length=255, verbose_name='نام و نام خانوادگی')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=255, unique=True, verbose_name='اسلاگ')),
                ('staff_type', models.CharField(choices=[('manager', 'مدیریت'), ('teacher', 'معلم'), ('advisor', 'مشاور'), ('administrative', 'اداری'), ('support', 'پشتیبانی'), ('other', 'سایر')], db_index=True, default='teacher', max_length=30, verbose_name='نوع عضو کادر')),
                ('role_title', models.CharField(blank=True, help_text='مثلاً مدیر مدرسه، معلم ریاضی، معاون آموزشی', max_length=255, null=True, verbose_name='عنوان نقش')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='معرفی کوتاه')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=apps.staff.models.staff_avatar_upload_to, validators=[apps.staff.validators.validate_staff_image_file], verbose_name='تصویر')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره تماس')),
                ('is_featured', models.BooleanField(db_index=True, default=False, verbose_name='ویژه؟')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_staff_members', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='departments.department', verbose_name='دپارتمان')),
                ('unit', models.ForeignKey(blank=True, help_text='فقط وقتی scope برابر unit است باید مقدار داشته باشد.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='units.schoolunit', verbose_name='واحد آموزشی')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_staff_members', to=settings.AUTH_USER_MODEL, verbose_name='آخرین ویرایش\u200cکننده')),
            ],
            options={
                'verbose_name': 'عضو کادر',
                'verbose_name_plural': 'کادر مدرسه',
                'ordering': ('order', 'full_name', '-id'),
                'indexes': [models.Index(fields=['is_active', 'order'], name='staff_staff_is_acti_641e7e_idx'), models.Index(fields=['scope', 'unit', 'is_active'], name='staff_staff_scope_a623dc_idx'), models.Index(fields=['staff_type', 'is_active'], name='staff_staff_staff_t_02015f_idx'), models.Index(fields=['department', 'is_active'], name='staff_staff_departm_a1ee97_idx'), models.Index(fields=['is_featured', 'order'], name='staff_staff_is_feat_ec4834_idx')],
            },
        ),
    ]
