# Generated by Django 6.0.6 on 2026-06-30 10:29

import apps.about.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال است؟')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.about.models.about_image_upload_to, verbose_name='تصویر')),
                ('meta_description', models.CharField(blank=True, max_length=300, null=True, verbose_name='توضیحات متا')),
            ],
            options={
                'verbose_name': 'صفحه درباره ما',
                'verbose_name_plural': 'صفحه درباره ما',
                'ordering': ('-is_active', '-updated_at', '-id'),
            },
        ),
    ]
