# Generated by Django 5.2.16 on 2026-07-30 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='founders',
            field=models.JSONField(blank=True, default=list, verbose_name='بنیان\u200cگذاران'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='goals',
            field=models.JSONField(blank=True, default=list, verbose_name='اهداف'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='history',
            field=models.TextField(blank=True, null=True, verbose_name='تاریخچه'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='images',
            field=models.JSONField(blank=True, default=list, verbose_name='تصاویر تکمیلی'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='key_people',
            field=models.JSONField(blank=True, default=list, verbose_name='افراد کلیدی'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='mission',
            field=models.TextField(blank=True, null=True, verbose_name='ماموریت'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='values',
            field=models.JSONField(blank=True, default=list, verbose_name='ارزش\u200cها'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='video_caption',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='زیرنویس ویدیو'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='video_description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیح ویدیو'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='video_poster_url',
            field=models.URLField(blank=True, max_length=2000, null=True, verbose_name='پوستر ویدیو'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='video_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان ویدیو'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='video_url',
            field=models.URLField(blank=True, max_length=2000, null=True, verbose_name='نشانی ویدیو'),
        ),
    ]
