# Generated by Django 5.2.16 on 2026-08-09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name="ContentRevision",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی")),
                ("content_kind", models.CharField(choices=[("news", "خبر"), ("announcement", "اطلاعیه")], max_length=20)),
                ("object_id", models.PositiveBigIntegerField()),
                ("snapshot", models.JSONField()),
                ("note", models.CharField(blank=True, max_length=255, null=True)),
                ("actor", models.ForeignKey(blank=True, null=True, on_delete=models.SET_NULL, related_name="content_revisions", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ("-created_at", "-id")},
        ),
        migrations.AddIndex(
            model_name="contentrevision",
            index=models.Index(fields=["content_kind", "object_id", "-created_at"], name="content_con_content_17c76d_idx"),
        ),
    ]
