# Generated by Django 6.0.6 on 2026-07-01 07:15

import apps.events.models
import apps.events.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('units', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال است؟')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('scope', models.CharField(choices=[('school', 'کل مدرسه'), ('unit', 'واحد آموزشی')], db_index=True, default='school', max_length=20, verbose_name='محدوده انتشار')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('waiting_review', 'در انتظار بررسی'), ('approved', 'تأیید شده'), ('published', 'منتشر شده'), ('rejected', 'رد شده'), ('archived', 'آرشیو شده')], db_index=True, default='draft', max_length=30, verbose_name='وضعیت')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان رویداد')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=255, unique=True, verbose_name='اسلاگ')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='خلاصه')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to=apps.events.models.event_cover_upload_to, validators=[apps.events.validators.validate_event_image_file], verbose_name='تصویر کاور')),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='متن جایگزین تصویر')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='محل برگزاری')),
                ('event_start_at', models.DateTimeField(db_index=True, verbose_name='زمان شروع رویداد')),
                ('event_end_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان پایان رویداد')),
                ('registration_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='لینک ثبت\u200cنام یا اطلاعات بیشتر')),
                ('published_at', models.DateField(blank=True, db_index=True, null=True, verbose_name='تاریخ انتشار')),
                ('is_featured', models.BooleanField(db_index=True, default=False, verbose_name='ویژه؟')),
                ('review_note', models.TextField(blank=True, null=True, verbose_name='یادداشت بررسی')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_events', to=settings.AUTH_USER_MODEL, verbose_name='منتشرکننده')),
                ('unit', models.ForeignKey(blank=True, help_text='فقط وقتی scope برابر unit است باید مقدار داشته باشد.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='units.schoolunit', verbose_name='واحد آموزشی')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_events', to=settings.AUTH_USER_MODEL, verbose_name='آخرین ویرایش\u200cکننده')),
            ],
            options={
                'verbose_name': 'رویداد',
                'verbose_name_plural': 'رویدادها',
                'ordering': ('event_start_at', 'order', '-id'),
                'indexes': [models.Index(fields=['status', 'published_at'], name='events_even_status_09cadc_idx'), models.Index(fields=['scope', 'unit', 'status'], name='events_even_scope_dc3644_idx'), models.Index(fields=['event_start_at', 'id'], name='events_even_event_s_c08c7a_idx'), models.Index(fields=['is_featured', 'event_start_at'], name='events_even_is_feat_ba4cd1_idx'), models.Index(fields=['is_active', 'status'], name='events_even_is_acti_9ac25b_idx')],
            },
        ),
    ]
