# Generated by Django 6.0.6 on 2026-07-01 06:16

import apps.achievements.models
import apps.achievements.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('units', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال است؟')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان افتخار')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=255, unique=True, verbose_name='اسلاگ')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='خلاصه')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to=apps.achievements.models.achievement_cover_upload_to, validators=[apps.achievements.validators.validate_achievement_image_file], verbose_name='تصویر')),
                ('achievement_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='تاریخ کسب افتخار')),
                ('is_featured', models.BooleanField(db_index=True, default=False, verbose_name='ویژه؟')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_achievements', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
                ('related_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achievements', to='units.schoolunit', verbose_name='واحد مرتبط')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_achievements', to=settings.AUTH_USER_MODEL, verbose_name='آخرین ویرایش\u200cکننده')),
            ],
            options={
                'verbose_name': 'افتخار',
                'verbose_name_plural': 'افتخارات',
                'ordering': ('order', '-achievement_date', '-id'),
                'indexes': [models.Index(fields=['is_active', 'order'], name='achievement_is_acti_0b8c48_idx'), models.Index(fields=['is_featured', 'achievement_date'], name='achievement_is_feat_526102_idx'), models.Index(fields=['related_unit', 'is_active'], name='achievement_related_bd5606_idx'), models.Index(fields=['achievement_date', 'id'], name='achievement_achieve_4d3b21_idx')],
            },
        ),
    ]
