# Generated by Django 6.0.8 on 2026-08-23 21:15
#
# Schema-only change -- no data migration needed. Confirmed via direct
# query against the dev DB before writing this migration that no user
# currently has more than one Address row with is_default=True:
#   select user_id, count(*) from shop_address where is_default=true
#     group by user_id having count(*) > 1;
#   -- (0 rows)
# so this AddConstraint is safe to apply as-is.

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_cart_item_nulls_not_distinct'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='address',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('user',), name='unique_default_address_per_user'),
        ),
    ]
