# Generated by Django 6.0.8 (hand-written -- Django is not installed in
# this environment to run makemigrations directly; matches the exact
# field definition added to apps/shop/models/cart.py's CartItem).
#
# Schema-only, additive change: a new CharField with blank=True,
# default="" backfills every existing row to "" (no supplied idempotency
# key), which is exactly add_item()'s documented fallback for a row that
# never went through the new client_request_id path -- no data migration
# needed.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_unique_default_address_per_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='last_add_request_id',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='شناسه درخواست افزودن'),
        ),
    ]
