# Generated by Django 6.0.8 on 2026-09-02 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_cartitem_recent_add_request_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='recent_add_request_ids',
            field=models.JSONField(blank=True, db_default=[], default=list, verbose_name='شناسه\u200cهای اخیر درخواست افزودن'),
        ),
    ]
