# Generated by Django 6.0.6 on 2026-06-22 10:02

import apps.accounts.models
import apps.accounts.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('units', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال است؟')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام کامل')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره تماس')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=apps.accounts.models.user_avatar_upload_to, validators=[apps.accounts.validators.validate_avatar_image_file], verbose_name='تصویر پروفایل')),
                ('role', models.CharField(choices=[('general_manager', 'مدیر کل'), ('unit_manager', 'مدیر واحد'), ('unit_media', 'مسئول رسانه واحد'), ('parent', 'والد')], db_index=True, default='parent', max_length=30, verbose_name='نقش')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پروفایل کاربر',
                'verbose_name_plural': 'پروفایل کاربران',
                'indexes': [models.Index(fields=['role', 'is_active'], name='accounts_us_role_af860b_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserUnitMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال است؟')),
                ('role', models.CharField(choices=[('unit_manager', 'مدیر واحد'), ('unit_media', 'مسئول رسانه واحد'), ('parent', 'والد')], db_index=True, max_length=30, verbose_name='نقش در واحد')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_memberships', to='units.schoolunit', verbose_name='واحد آموزشی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_memberships', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'عضویت کاربر در واحد',
                'verbose_name_plural': 'عضویت کاربران در واحدها',
                'ordering': ('unit__order', 'unit__id', 'id'),
                'indexes': [models.Index(fields=['user', 'role', 'is_active'], name='accounts_us_user_id_2a4f2c_idx'), models.Index(fields=['unit', 'role', 'is_active'], name='accounts_us_unit_id_1a15db_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'unit', 'role'), name='unique_user_unit_role_membership')],
            },
        ),
    ]
