# Generated by Django 5.2.17 on 2026-08-09 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserInvitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "token_hash",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="هش توکن"
                    ),
                ),
                ("expires_at", models.DateTimeField(verbose_name="تاریخ انقضا")),
                (
                    "used_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاریخ استفاده"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_invitations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ایجادکننده",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر دعوت\u200cشده",
                    ),
                ),
            ],
            options={
                "verbose_name": "دعوت\u200cنامه تعیین رمز عبور",
                "verbose_name_plural": "دعوت\u200cنامه\u200cهای تعیین رمز عبور",
                "ordering": ("-created_at", "-id"),
            },
        ),
    ]
