# Generated by Django 6.0.6 on 2026-06-30 10:29

import apps.home.models
import apps.home.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال است؟')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان')),
                ('subtitle', models.CharField(blank=True, max_length=500, null=True, verbose_name='زیرعنوان')),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.home.models.home_slide_image_upload_to, validators=[apps.home.validators.validate_home_slide_image_file], verbose_name='تصویر')),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='متن جایگزین')),
                ('href', models.CharField(blank=True, help_text='می\u200cتواند مسیر داخلی مثل /about یا لینک کامل باشد.', max_length=500, null=True, verbose_name='لینک')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_home_slides', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_home_slides', to=settings.AUTH_USER_MODEL, verbose_name='آخرین ویرایش\u200cکننده')),
            ],
            options={
                'verbose_name': 'اسلاید صفحه اصلی',
                'verbose_name_plural': 'اسلایدهای صفحه اصلی',
                'ordering': ('order', '-id'),
                'indexes': [models.Index(fields=['is_active', 'order'], name='home_homesl_is_acti_dd1739_idx'), models.Index(fields=['order', 'id'], name='home_homesl_order_b410d2_idx')],
            },
        ),
    ]
