# Generated by Django 6.0.6 on 2026-07-01 06:22

import apps.gallery.models
import apps.gallery.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('units', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال است؟')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('scope', models.CharField(choices=[('school', 'کل مدرسه'), ('unit', 'واحد آموزشی')], db_index=True, default='school', max_length=20, verbose_name='محدوده انتشار')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('waiting_review', 'در انتظار بررسی'), ('approved', 'تأیید شده'), ('published', 'منتشر شده'), ('rejected', 'رد شده'), ('archived', 'آرشیو شده')], db_index=True, default='draft', max_length=30, verbose_name='وضعیت')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان تصویر')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=255, unique=True, verbose_name='اسلاگ')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='توضیح کوتاه')),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.gallery.models.gallery_image_upload_to, validators=[apps.gallery.validators.validate_gallery_image_file], verbose_name='تصویر')),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='متن جایگزین')),
                ('caption', models.CharField(blank=True, max_length=500, null=True, verbose_name='کپشن')),
                ('event_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='تاریخ رویداد')),
                ('published_at', models.DateField(blank=True, db_index=True, null=True, verbose_name='تاریخ انتشار')),
                ('is_featured', models.BooleanField(db_index=True, default=False, verbose_name='ویژه؟')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_gallery_items', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_gallery_items', to=settings.AUTH_USER_MODEL, verbose_name='منتشرکننده')),
                ('unit', models.ForeignKey(blank=True, help_text='فقط وقتی scope برابر unit است باید مقدار داشته باشد.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='units.schoolunit', verbose_name='واحد آموزشی')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_gallery_items', to=settings.AUTH_USER_MODEL, verbose_name='آخرین ویرایش\u200cکننده')),
            ],
            options={
                'verbose_name': 'آیتم گالری',
                'verbose_name_plural': 'آیتم\u200cهای گالری',
                'ordering': ('order', '-published_at', '-id'),
                'indexes': [models.Index(fields=['status', 'published_at'], name='gallery_gal_status_10da2d_idx'), models.Index(fields=['scope', 'status'], name='gallery_gal_scope_adf65f_idx'), models.Index(fields=['unit', 'status'], name='gallery_gal_unit_id_5faddc_idx'), models.Index(fields=['is_featured', 'published_at'], name='gallery_gal_is_feat_9269a6_idx'), models.Index(fields=['is_active', 'status'], name='gallery_gal_is_acti_cfd214_idx'), models.Index(fields=['order', 'id'], name='gallery_gal_order_fef916_idx')],
            },
        ),
    ]
