# Generated by Django 5.2.16 on 2026-07-30 05:45

import apps.gallery.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_galleryitem_frontend_media_fields'),
        ('units', '0005_schoolunit_accepts_registration_schoolunit_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('file', models.FileField(upload_to=apps.gallery.models.media_asset_upload_to, verbose_name='فایل')),
                ('media_type', models.CharField(choices=[('image', 'تصویر'), ('video', 'ویدئو')], db_index=True, max_length=20)),
                ('content_type', models.CharField(max_length=100)),
                ('size', models.PositiveBigIntegerField()),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('caption', models.CharField(blank=True, max_length=500)),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_assets', to='units.schoolunit')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_media_assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['unit', 'media_type'], name='gallery_med_unit_id_91fb15_idx'), models.Index(fields=['uploaded_by', 'created_at'], name='gallery_med_uploade_6486bc_idx')],
            },
        ),
    ]
