# Generated by Django 6.0.6 on 2026-06-28 10:57

import apps.announcements.models
import apps.announcements.utils
import apps.announcements.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('units', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال است؟')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان دسته\u200cبندی اطلاعیه')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=255, unique=True, verbose_name='اسلاگ')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی اطلاعیه',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای اطلاعیه',
                'ordering': ('order', 'id'),
                'indexes': [models.Index(fields=['is_active', 'order'], name='announcemen_is_acti_083088_idx')],
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال است؟')),
                ('scope', models.CharField(choices=[('school', 'کل مدرسه'), ('unit', 'واحد آموزشی')], db_index=True, default='school', max_length=20, verbose_name='محدوده انتشار')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('waiting_review', 'در انتظار بررسی'), ('approved', 'تأیید شده'), ('published', 'منتشر شده'), ('rejected', 'رد شده'), ('archived', 'آرشیو شده')], db_index=True, default='draft', max_length=30, verbose_name='وضعیت')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان اطلاعیه')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=255, unique=True, verbose_name='اسلاگ')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='خلاصه اطلاعیه')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to=apps.announcements.models.announcement_cover_upload_to, validators=[apps.announcements.validators.validate_announcement_image_file], verbose_name='تصویر کاور')),
                ('content_json', models.JSONField(blank=True, default=apps.announcements.utils.default_announcement_content_json, verbose_name='محتوای ساختاریافته')),
                ('content_text', models.TextField(blank=True, db_index=True, editable=False, null=True, verbose_name='متن ساده برای جستجو')),
                ('published_at', models.DateField(blank=True, db_index=True, null=True, verbose_name='تاریخ انتشار')),
                ('is_featured', models.BooleanField(db_index=True, default=False, verbose_name='اطلاعیه ویژه؟')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_announcements', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_announcements', to=settings.AUTH_USER_MODEL, verbose_name='منتشرکننده')),
                ('unit', models.ForeignKey(blank=True, help_text='فقط وقتی scope برابر unit است باید مقدار داشته باشد.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='units.schoolunit', verbose_name='واحد آموزشی')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_announcements', to=settings.AUTH_USER_MODEL, verbose_name='آخرین ویرایش\u200cکننده')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='announcements.announcementcategory', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'اطلاعیه',
                'verbose_name_plural': 'اطلاعیه\u200cها',
                'ordering': ('-published_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='AnnouncementMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.announcements.models.announcement_content_image_upload_to, validators=[apps.announcements.validators.validate_announcement_image_file], verbose_name='تصویر')),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='متن جایگزین')),
                ('caption', models.CharField(blank=True, max_length=500, null=True, verbose_name='کپشن')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ آپلود')),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_items', to='announcements.announcement', verbose_name='اطلاعیه')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_announcement_media', to=settings.AUTH_USER_MODEL, verbose_name='آپلودکننده')),
            ],
            options={
                'verbose_name': 'رسانه اطلاعیه',
                'verbose_name_plural': 'رسانه\u200cهای اطلاعیه',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['status', 'published_at'], name='announcemen_status_a4da61_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['scope', 'status'], name='announcemen_scope_d8cbd6_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['unit', 'status'], name='announcemen_unit_id_112bfd_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['is_featured', 'published_at'], name='announcemen_is_feat_33af43_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['category', 'status'], name='announcemen_categor_52bdc9_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['is_active', 'status'], name='announcemen_is_acti_b4c92d_idx'),
        ),
    ]
