# Generated by Django 5.2.16 on 2026-08-09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("announcements", "0002_announcement_cover_image_url")]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="editor_json",
            field=models.JSONField(
                blank=True,
                help_text="نمایش بدون تبدیل سند Tiptap برای ویرایش مجدد.",
                null=True,
                verbose_name="سند اصلی ویرایشگر",
            ),
        ),
    ]
