# Generated by Django 5.2.17 on 2026-08-09 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("announcements", "0003_announcement_editor_json"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="canonical_url",
            field=models.URLField(
                blank=True, max_length=2000, null=True, verbose_name="نشانی کنونیکال"
            ),
        ),
        migrations.AddField(
            model_name="announcement",
            name="focus_keyphrase",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="عبارت کلیدی کانونی"
            ),
        ),
        migrations.AddField(
            model_name="announcement",
            name="is_cornerstone",
            field=models.BooleanField(default=False, verbose_name="محتوای محوری"),
        ),
        migrations.AddField(
            model_name="announcement",
            name="is_followable",
            field=models.BooleanField(
                default=True, verbose_name="قابل دنبال\u200cکردن پیوندهای صفحه"
            ),
        ),
        migrations.AddField(
            model_name="announcement",
            name="is_indexable",
            field=models.BooleanField(
                default=True, verbose_name="قابل نمایه\u200cسازی در موتورهای جستجو"
            ),
        ),
        migrations.AddField(
            model_name="announcement",
            name="meta_description",
            field=models.CharField(
                blank=True, max_length=300, null=True, verbose_name="توضیحات متا"
            ),
        ),
        migrations.AddField(
            model_name="announcement",
            name="og_description",
            field=models.CharField(
                blank=True,
                max_length=300,
                null=True,
                verbose_name="توضیح اشتراک\u200cگذاری اجتماعی",
            ),
        ),
        migrations.AddField(
            model_name="announcement",
            name="og_image_url",
            field=models.TextField(
                blank=True, null=True, verbose_name="نشانی تصویر اشتراک\u200cگذاری"
            ),
        ),
        migrations.AddField(
            model_name="announcement",
            name="og_title",
            field=models.CharField(
                blank=True,
                max_length=95,
                null=True,
                verbose_name="عنوان اشتراک\u200cگذاری اجتماعی",
            ),
        ),
        migrations.AddField(
            model_name="announcement",
            name="seo_title",
            field=models.CharField(
                blank=True, max_length=70, null=True, verbose_name="عنوان سئو"
            ),
        ),
    ]
