# Generated by Django 6.0.6 on 2026-07-01 06:22

import apps.news.models
import apps.news.utils
import apps.news.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('units', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال است؟')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان دسته\u200cبندی')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, help_text='برای فیلتر کردن خبرها استفاده می\u200cشود. اگر خالی بماند، از عنوان ساخته می\u200cشود.', max_length=255, unique=True, verbose_name='اسلاگ')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی خبر',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای خبر',
                'ordering': ('order', 'id'),
                'indexes': [models.Index(fields=['is_active', 'order'], name='news_newsca_is_acti_489021_idx')],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال است؟')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان خبر')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, help_text='برای URL صفحه جزئیات استفاده می\u200cشود. اگر خالی بماند، از عنوان ساخته می\u200cشود.', max_length=255, unique=True, verbose_name='اسلاگ')),
                ('scope', models.CharField(choices=[('school', 'کل مدرسه'), ('unit', 'واحد آموزشی')], db_index=True, default='school', max_length=20, verbose_name='محدوده انتشار')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='خلاصه خبر')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to=apps.news.models.news_cover_upload_to, validators=[apps.news.validators.validate_news_image_file], verbose_name='تصویر کاور')),
                ('content_json', models.JSONField(blank=True, default=apps.news.utils.default_news_content_json, help_text='خروجی JSON ادیتور خبر. برای نمایش در فرانت استفاده می\u200cشود.', verbose_name='محتوای ساختاریافته')),
                ('content_text', models.TextField(blank=True, db_index=True, editable=False, null=True, verbose_name='متن ساده برای جستجو')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('waiting_review', 'در انتظار بررسی'), ('approved', 'تأیید شده'), ('published', 'منتشر شده'), ('rejected', 'رد شده'), ('archived', 'آرشیو شده')], db_index=True, default='draft', max_length=30, verbose_name='وضعیت')),
                ('published_at', models.DateField(blank=True, db_index=True, help_text='برای نمایش عمومی خبر، تاریخ انتشار باید واقعی و امروز یا قبل\u200cتر باشد.', null=True, verbose_name='تاریخ انتشار')),
                ('is_featured', models.BooleanField(db_index=True, default=False, verbose_name='خبر ویژه؟')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_news_items', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_news_items', to=settings.AUTH_USER_MODEL, verbose_name='منتشرکننده')),
                ('unit', models.ForeignKey(blank=True, help_text='فقط وقتی scope برابر unit است باید مقدار داشته باشد.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_items', to='units.schoolunit', verbose_name='واحد آموزشی')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_news_items', to=settings.AUTH_USER_MODEL, verbose_name='آخرین ویرایش\u200cکننده')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_items', to='news.newscategory', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'خبر',
                'verbose_name_plural': 'اخبار و اطلاعیه\u200cها',
                'ordering': ('-published_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='NewsMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.news.models.news_content_image_upload_to, validators=[apps.news.validators.validate_news_image_file], verbose_name='تصویر')),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='متن جایگزین')),
                ('caption', models.CharField(blank=True, max_length=500, null=True, verbose_name='کپشن')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ آپلود')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_items', to='news.news', verbose_name='خبر')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_news_media', to=settings.AUTH_USER_MODEL, verbose_name='آپلودکننده')),
            ],
            options={
                'verbose_name': 'رسانه خبر',
                'verbose_name_plural': 'رسانه\u200cهای خبر',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['status', 'published_at'], name='news_news_status_e22a00_idx'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['scope', 'status'], name='news_news_scope_0a987b_idx'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['unit', 'status'], name='news_news_unit_id_494a94_idx'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['is_featured', 'published_at'], name='news_news_is_feat_d10cee_idx'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['category', 'status'], name='news_news_categor_caf58c_idx'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['is_active', 'status'], name='news_news_is_acti_256fe8_idx'),
        ),
    ]
