# Generated by Django 6.0.6 on 2026-06-22 08:53

import apps.news.models
import apps.news.utils
import apps.news.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = []
