# Generated by Django 5.2.16 on 2026-07-30 05:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_news_cover_image_url'),
        ('units', '0005_schoolunit_accepts_registration_schoolunit_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_important',
            field=models.BooleanField(db_index=True, default=False, verbose_name='خبر مهم؟'),
        ),
        migrations.AddField(
            model_name='news',
            name='priority',
            field=models.PositiveSmallIntegerField(db_index=True, default=0, help_text='عدد بزرگ\u200cتر در چیدمان خبرهای مهم زودتر نمایش داده می\u200cشود.', verbose_name='اولویت نمایش'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['is_important', 'priority'], name='news_news_is_impo_aa66c7_idx'),
        ),
    ]
