# Generated by Django 5.2.16 on 2026-08-09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("news", "0005_news_is_important_news_priority_and_more")]

    operations = [
        migrations.AddField(
            model_name="news",
            name="editor_json",
            field=models.JSONField(
                blank=True,
                help_text="نمایش بدون تبدیل سند Tiptap برای ویرایش مجدد.",
                null=True,
                verbose_name="سند اصلی ویرایشگر",
            ),
        ),
    ]
