# Generated by Django 6.0.8 on 2026-09-02 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_sanitize_legacy_table_colwidths'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='version',
            field=models.PositiveIntegerField(default=1, verbose_name='نسخه'),
        ),
    ]
