# Generated by Django 6.0.6 on 2026-07-01 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال است؟')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان دپارتمان')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, help_text='برای URL صفحه جزئیات استفاده می\u200cشود. اگر خالی بماند، از عنوان ساخته می\u200cشود.', max_length=255, unique=True, verbose_name='اسلاگ')),
                ('short_description', models.CharField(blank=True, max_length=500, null=True, verbose_name='توضیح کوتاه')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات کامل')),
                ('icon', models.FileField(blank=True, help_text='می\u200cتواند SVG، PNG یا فایل تصویری معتبر باشد. اگر آیکون تأییدشده ندارید، خالی بگذارید.', null=True, upload_to='departments/icons/', verbose_name='آیکون')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='departments/covers/', verbose_name='تصویر کاور')),
            ],
            options={
                'verbose_name': 'دپارتمان',
                'verbose_name_plural': 'دپارتمان\u200cها',
                'ordering': ('order', 'id'),
            },
        ),
    ]
