# Generated by Django 6.0.8 on 2026-08-14 11:53

import apps.virtual_tour.models
import apps.virtual_tour.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0002_department_cover_image_url'),
        ('units', '0005_schoolunit_accepts_registration_schoolunit_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TourScene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال است؟')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('waiting_review', 'در انتظار بررسی'), ('approved', 'تأیید شده'), ('published', 'منتشر شده'), ('rejected', 'رد شده'), ('archived', 'آرشیو شده')], db_index=True, default='draft', max_length=30, verbose_name='وضعیت')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان صحنه')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=255, unique=True, verbose_name='اسلاگ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('panorama', models.ImageField(blank=True, null=True, upload_to=apps.virtual_tour.models.panorama_upload_to, validators=[apps.virtual_tour.validators.validate_panorama_image_file], verbose_name='تصویر پانورامای ۳۶۰ درجه')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=apps.virtual_tour.models.thumbnail_upload_to, validators=[apps.virtual_tour.validators.validate_thumbnail_image_file], verbose_name='تصویر بندانگشتی')),
                ('initial_yaw', models.FloatField(default=0, verbose_name='زاویه افقی شروع')),
                ('initial_pitch', models.FloatField(default=0, verbose_name='زاویه عمودی شروع')),
                ('initial_hfov', models.FloatField(default=105, verbose_name='زاویه دید افقی شروع')),
                ('is_default', models.BooleanField(db_index=True, default=False, verbose_name='صحنه پیش\u200cفرض این در؟')),
                ('published_at', models.DateField(blank=True, null=True, verbose_name='تاریخ انتشار')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tour_scenes', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tour_scenes', to='departments.department', verbose_name='دپارتمان')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_tour_scenes', to=settings.AUTH_USER_MODEL, verbose_name='منتشرکننده')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tour_scenes', to='units.schoolunit', verbose_name='واحد آموزشی')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_tour_scenes', to=settings.AUTH_USER_MODEL, verbose_name='آخرین ویرایش\u200cکننده')),
            ],
            options={
                'verbose_name': 'صحنه تور مجازی',
                'verbose_name_plural': 'صحنه\u200cهای تور مجازی',
                'ordering': ('unit_id', 'department_id', 'order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='TourHotspot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('yaw', models.FloatField(verbose_name='زاویه افقی')),
                ('pitch', models.FloatField(verbose_name='زاویه عمودی')),
                ('label', models.CharField(blank=True, max_length=100, verbose_name='برچسب')),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotspots', to='virtual_tour.tourscene', verbose_name='صحنه مبدأ')),
                ('target_scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_hotspots', to='virtual_tour.tourscene', verbose_name='صحنه مقصد')),
            ],
            options={
                'verbose_name': 'نقطه اتصال تور مجازی',
                'verbose_name_plural': 'نقاط اتصال تور مجازی',
                'ordering': ('scene_id', 'order', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='tourscene',
            index=models.Index(fields=['unit', 'status'], name='virtual_tou_unit_id_ae6aed_idx'),
        ),
        migrations.AddIndex(
            model_name='tourscene',
            index=models.Index(fields=['department', 'status'], name='virtual_tou_departm_a7e146_idx'),
        ),
        migrations.AddIndex(
            model_name='tourscene',
            index=models.Index(fields=['is_active', 'status'], name='virtual_tou_is_acti_a324b4_idx'),
        ),
        migrations.AddIndex(
            model_name='tourhotspot',
            index=models.Index(fields=['scene'], name='virtual_tou_scene_i_cd35d5_idx'),
        ),
    ]
