# Generated by Django 6.0.6 on 2026-07-01 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال است؟')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان واحد آموزشی')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, help_text='برای URL صفحه جزئیات استفاده می\u200cشود. اگر خالی بماند، از عنوان ساخته می\u200cشود.', max_length=255, unique=True, verbose_name='اسلاگ')),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True, verbose_name='زیرعنوان')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='units/covers/', verbose_name='تصویر کاور')),
                ('age_range', models.CharField(blank=True, max_length=100, null=True, verbose_name='بازه سنی')),
                ('grade_range', models.CharField(blank=True, max_length=100, null=True, verbose_name='پایه\u200cهای تحصیلی')),
            ],
            options={
                'verbose_name': 'واحد آموزشی',
                'verbose_name_plural': 'واحدهای آموزشی',
                'ordering': ('order', 'id'),
            },
        ),
    ]
