# Generated by Django 6.0.6 on 2026-07-07 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolunit',
            name='gender',
            field=models.TextField(choices=[('boys', 'پسرانه'), ('girls', 'دخترانه'), ('mixed', 'مختلط')], db_index=True, default='boys', max_length=20, verbose_name='جنسیت'),
        ),
        migrations.AddField(
            model_name='schoolunit',
            name='kind',
            field=models.TextField(choices=[('presvhool', 'پیش دبستانی'), ('elementary', 'دبستان'), ('middle_school', 'متوسطه اول'), ('high_school', 'دبیرستان')], db_index=True, default='elementary', max_length=30, verbose_name='نوع واحد'),
        ),
    ]
