# Generated by Django 5.2.16 on 2026-07-30 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0004_alter_schoolunit_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolunit',
            name='accepts_registration',
            field=models.BooleanField(db_index=True, default=True, verbose_name='پیش\u200cثبت\u200cنام فعال است؟'),
        ),
        migrations.AddField(
            model_name='schoolunit',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='نشانی'),
        ),
        migrations.AddField(
            model_name='schoolunit',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل'),
        ),
        migrations.AddField(
            model_name='schoolunit',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='عرض جغرافیایی'),
        ),
        migrations.AddField(
            model_name='schoolunit',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='طول جغرافیایی'),
        ),
        migrations.AddField(
            model_name='schoolunit',
            name='map_url',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='لینک نقشه'),
        ),
        migrations.AddField(
            model_name='schoolunit',
            name='office_hours',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ساعات پاسخ\u200cگویی'),
        ),
        migrations.AddField(
            model_name='schoolunit',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره تماس اصلی'),
        ),
        migrations.AddField(
            model_name='schoolunit',
            name='phone_secondary',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره تماس دوم'),
        ),
    ]
