# Generated by Django 6.0.8 on 2026-08-17 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0005_schoolunit_accepts_registration_schoolunit_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolunit',
            name='is_internal',
            field=models.BooleanField(db_index=True, default=False, help_text='برای واحدهای غیرواقعی که فقط برای اتصال حساب\u200cهای آزمایشی/توسعه ساخته شده\u200cاند. این واحدها در سایت عمومی، فرم ثبت\u200cنام، فرم تماس و آمارهای گزارش\u200cگیری نمایش داده نمی\u200cشوند.', verbose_name='واحد داخلی/غیرعمومی است؟'),
        ),
    ]
